
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package gzt;

import java.util.logging.Logger;

import service.Code;
import service.ReturnResult;

/**
 * This class was generated by Apache CXF 3.2.5 2018-08-02T14:01:59.443+08:00
 * Generated source version: 3.2.5
 *
 */
@javax.jws.WebService(serviceName = "QueryValidatorServicesService", portName = "QueryValidatorServices", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn",

		endpointInterface = "gzt.QueryValidatorServices")

public class QueryValidatorServicesImpl implements QueryValidatorServices {

	private static final Logger LOG = Logger.getLogger(QueryValidatorServicesImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see gzt.QueryValidatorServices#querySingle(java.lang.String userName,
	 * java.lang.String password, java.lang.String type, java.lang.String
	 * param)*
	 */
	public java.lang.String querySingle(java.lang.String userName, java.lang.String password, java.lang.String type,
			java.lang.String param) {
		LOG.info("Executing operation querySingle");
		try {
			System.out.println("userName:" + Code.Decode(userName));
			System.out.println("password:" + Code.Decode(password));
			System.out.println("type:" + Code.Decode(type));
		} catch (Exception e2) {
			e2.printStackTrace();
		}

		System.out.println("服务器端收到的未解密的param:" + param);

		try {
			param = Code.Decode(param);
		} catch (Exception e1) {
			e1.printStackTrace();
		}

		System.out.println("服务器端解密之后的param:" + param);
		return ReturnResult.returnResult(param);

	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see gzt.QueryValidatorServices#queryBatch(java.lang.String userName,
	 * java.lang.String password, java.lang.String type, java.lang.String
	 * param)*
	 */
	public java.lang.String queryBatch(java.lang.String userName, java.lang.String password, java.lang.String type,
			java.lang.String param) {
		LOG.info("Executing operation queryBatch");
		System.out.println("userName:"+userName);
		System.out.println("password"+password);
		System.out.println("type"+type);
		System.out.println("type"+param);
		try {
			java.lang.String _return = "";
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}

	}

}
