package gzt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-02T14:01:59.473+08:00
 * Generated source version: 3.2.5
 *
 */
//wsdlLocation = "file:/C:/Users/wangshaojie/Desktop/queryValidatorServices.wsdl",
@WebServiceClient(name = "QueryValidatorServicesService",
                  
                  targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
public class QueryValidatorServicesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://app.service.validator.businesses.gboss.id5.cn", "QueryValidatorServicesService");
    public final static QName QueryValidatorServices = new QName("http://app.service.validator.businesses.gboss.id5.cn", "QueryValidatorServices");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/wangshaojie/Desktop/queryValidatorServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryValidatorServicesService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/wangshaojie/Desktop/queryValidatorServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryValidatorServicesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryValidatorServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryValidatorServicesService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public QueryValidatorServicesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QueryValidatorServicesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QueryValidatorServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns QueryValidatorServices
     */
    @WebEndpoint(name = "QueryValidatorServices")
    public QueryValidatorServices getQueryValidatorServices() {
        return super.getPort(QueryValidatorServices, QueryValidatorServices.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryValidatorServices
     */
    @WebEndpoint(name = "QueryValidatorServices")
    public QueryValidatorServices getQueryValidatorServices(WebServiceFeature... features) {
        return super.getPort(QueryValidatorServices, QueryValidatorServices.class, features);
    }

}
