package gzt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-02T14:01:59.460+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", name = "QueryValidatorServices")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryValidatorServices {

    @WebMethod
    @RequestWrapper(localName = "querySingle", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", className = "gzt.QuerySingle")
    @ResponseWrapper(localName = "querySingleResponse", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", className = "gzt.QuerySingleResponse")
    @WebResult(name = "querySingleReturn", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
    public java.lang.String querySingle(
        @WebParam(name = "userName_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String userName,
        @WebParam(name = "password_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String password,
        @WebParam(name = "type_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String type,
        @WebParam(name = "param_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String param
    );

    @WebMethod
    @RequestWrapper(localName = "queryBatch", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", className = "gzt.QueryBatch")
    @ResponseWrapper(localName = "queryBatchResponse", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", className = "gzt.QueryBatchResponse")
    @WebResult(name = "queryBatchReturn", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
    public java.lang.String queryBatch(
        @WebParam(name = "userName_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String userName,
        @WebParam(name = "password_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String password,
        @WebParam(name = "type_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String type,
        @WebParam(name = "param_", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn")
        java.lang.String param
    );
}
