
package gzt;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-02T14:01:59.470+08:00
 * Generated source version: 3.2.5
 *
 */

public class QueryValidatorServices_QueryValidatorServices_Server{

    protected QueryValidatorServices_QueryValidatorServices_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new QueryValidatorServicesImpl();
        String address = "http://172.21.131.70:6666/services/QueryValidatorServices";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new QueryValidatorServices_QueryValidatorServices_Server();
        System.out.println("Server ready...");

//        Thread.sleep(5 * 60 * 1000);
//        System.out.println("Server exiting");
//        System.exit(0);
    }
}
